<a href="https://colab.research.google.com/github/kenilv/woc4.0-ml-sentiment-analysis-Kenil-Vaghasiya/blob/main/Copy_of_NumPy_exercises_Kenil_Vaghasiya_WoC_4_0_(ML).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Part 1: Creating ndarrays

1. Convert the below given list of strings to an int32 NumPy array

In [ ]:
slist = ['2.5', '1.25', '0.024','2.999','1024.5']

In [ ]:
dummy = np.array(slist)
temp = dummy.astype(float)
answer= temp.astype(int)
print(answer)

[   2    1    0    2 1024]


2. Create an empty 5x5 NumPy matrix

In [ ]:
answer1 = np.empty((5, 5))
# Write your code here

# Part 2: Operations between Arrays and Scalars

3. Create a 1x7 Numpy array whose elements consist of a geometric progression with a = 1 & r = 3, terms are arranged indexwise, for ex

In [ ]:
sample_output = [1,3,9,27,81]

In [ ]:
gp = [1 * 3**i for i in range(7)]
answer2 = np.array(gp)
print(answer2)
# Write your code here

[  1   3   9  27  81 243 729]


4. Transform each of the element of the below matrix according to the below equation

    if x is an elements in input matrix, output matrix should have 
$1/(x^2 + 1)$ in its place



In [ ]:
mat = [[1,2,3],[4,5,6]]

In [ ]:
def myfunc(z):
    return 1/(1+ z**2)

answer2a = np.vectorize(myfunc)(mat)
print(answer2a)
# Write your code here

[[0.5        0.2        0.1       ]
 [0.05882353 0.03846154 0.02702703]]


# Part 3: Basic Indexing and Slicing

5. Make a 5x5 NumPy array of all zeros and use indexing and broadcasting to modify it such that all the elements not on the border are 1, for example

In [ ]:
output_sample = np.array([[0,0,0,0,0],[0,1,1,1,0],[0,1,1,1,0],[0,1,1,1,0],[0,0,0,0,0]])
output_sample

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
temp2 = np.array([[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]])
for i in range(5):
  for j in range(5):
    if(i==0 or j==0 or i==4 or j==4):
      temp2[i][j]=0
    else:
      temp2[i][j]=1
temp2
#write your code here

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

6. Given the 3x3x3, 3-dimensional NumPy array

In [ ]:
arr = np.arange(27).reshape((3,3,3))
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

i. Slice this matrix to contain only second and third rows, first and second columns of the given matrix.

In [ ]:
sample_output = np.array([[[3,4],[6,7]],[[12,13],[15,16]],[[21,22],[24,25]]])
sample_output

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

In [ ]:
arr1 = [[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]]
arr2 = np.array(arr1)
answer3 = arr2[:,1:3,0:2]
answer3
#write your code here

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

ii. Output a two dimensional matrix as shown below

In [ ]:
sample_output = np.array([[0,3,6],[9,12,15],[18,21,14]])
sample_output

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 14]])

In [ ]:
x = np.empty((3, 3),dtype='int')
counter = 0
for i in range(3):
  for j in range(3):
    x[i][j]=counter
    counter = counter + 3
x
#write your code here

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

# Part 4: Boolean Indexing

7. Given the following array, modify it such that even values stay the same and output contains 0s instead of odd values

In [ ]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
sample_output = np.array([[0,0,2],[0,4,0],[6,0,8]])
sample_output

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

In [ ]:
answer4 = np.arange(9).reshape((3,3))
for i in range(3):
  for j in range(3):
    if answer4[i][j]%2 == 1:
      answer4[i][j] = 0
answer4
#write your code here

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

# Part 5: Fancy Indexing

8. For the given matrix, use fancy indexing to output a 2d matrix consisting all the even elements of the given matrix

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
sample_output = np.array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])
sample_output

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

In [ ]:
answer5 = np.arange(32).reshape((8, 4))
answer5 = np.delete(answer5, 1, 1)
answer5 = np.delete(answer5, 2, 1)
answer5
# Write your code here

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

# Part 6: Expressing Conditional Logic as Array Operations



Given two following matrices, use conditional logic to replace all the odd elements of matrix A with even elements of matrix B

In [ ]:
A = np.arange(9).reshape((3,3))
B = np.arange(1,10).reshape((3,3))
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
sample_output = np.array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])
sample_output

array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])

In [ ]:
A1 = np.arange(9).reshape((3,3))
B1 = np.arange(1,10).reshape((3,3))
for i in range(3):
  for j in range(3):
    if A1[i][j]%2 == 1:
      A1[i][j] = B1[i][j]

A1  
# Write your code here

array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])

# Part 7: Linear Algebra

Given the following system of equations, solve for x and y using either `numpy.linalg.solve(m1,m2)` or using `inv` and `dot`

2x + 5y = 20

3x + 6y = 12

In [ ]:
a = np.array(([[2, 5], [3, 6]]),dtype='int')
b = np.array(([20, 12]),dtype='int')
x = np.linalg.solve(a, b)
answer7 = x.astype(int)
answer7
#write your code here

array([-20,  12])